### ISSUE TITLE
Current version is not published to rubygems.

### ISSUE THREAD

**Issue by MaciejSzczepanski** [pattex/jekyll-tagging#55]
Version 1.0.1 does not work properly with Jekyll 3.2.x, however you've already fix it in issue #51 - can you publish current master?

**Comment by pattex** [comment]
I will. But first there is a little pile of issues I want to take a look at. Sadly time is a rare good for me. But it will happen.

**Comment by nhoizey** [comment]
@pattex couldn't you release a 1.1.0 fixing the compatibility issue, and then a 1.1.1 or 1.2.0 later with the other fixes?

**Comment by ke352802081770314** [comment]
I think it would be a real service to users if you could kindly just publish your current state as a rubygem version. I recently updated my FreeBSD machine with the slew of rubygems (from packages) and ended up with a nonworking jekyll setup, which worked previously. Seeing nested posts where just the tags were supposed to be throws the layout and content in a big way!
Running into such problems causes disappointment in your gem, is disruptive when updating existing installations, and quite a headache to figure out how to fix. Not every jekyll user is a ruby developer or git specialist! Since I don't use bundler, my workaround was to copy the tagging.rb here into /usr/local/lib/ruby/gems/2.2/gems/jekyll-tagging-1.0.1/lib/jekyll/tagging.rb essentially faking it.
So again, please release what you have, further enhancements can wait.
Many thanks for your consideration.

**Comment by ElectricRCAircraftGuy** [comment]
This problem still exists. My tags page shows: `Jekyll::Drops::SiteDrop`
