### ISSUE TITLE
Tag cloud not compatible with Jekyll 3.1+

### ISSUE THREAD

**Issue by justinjaywang** [pattex/jekyll-tagging#56]
`{{ site | tag_cloud }}` isn't compatible with [Liquid drops](https://jekyllrb.com/news/2016/01/24/jekyll-3-1-0-released/) starting in Jekyll 3.1.

Here's what it outputs:

```
Jekyll::Drops::SiteDrop
```

**Comment by solars** [comment]
Came across the same issue .. does anyone have a solution yet?

**Comment by nhoizey** [comment]
It's a known issue: #51 

Unfortunately, @pattex didn't yet publish the fix on rubygems, but closed the issue asking for it… #55

**Comment by solars** [comment]
@nhoizey thank you

@pattex what's the current state?

**Comment by nhoizey** [comment]
@solars if you use Bundler to install your plugins, you can (temporarily) use current version from Github instead of the packaged version from Rubygems.

Here is [how I do it myself](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/Gemfile#L11):

```
gem 'jekyll-tagging', :git => 'https://github.com/pattex/jekyll-tagging.git'
```

You will have to remove this as soon as @pattex releases the gem, to prevent side effects during new developments.

**Comment by solars** [comment]
@nhoizey I did the same - for the time being. I noticed many people asked about so I wondered about the status.
Thanks a lot for the suggestion!

**Comment by nhoizey** [comment]
@solars you're welcome!
